"""
Plot training loss curve from saved results.

Note: text report (report.txt) is auto-generated by training.
      This script only generates the loss curve plot.

Usage:
    cd LSTM_baseline
    python src/visualize.py
"""

import os
import pickle
import argparse

import numpy as np


def load_results(path: str) -> dict:
    with open(path, "rb") as f:
        return pickle.load(f)


def plot_loss_curve(results: dict, output_dir: str, show: bool = True):
    """Plot training + validation loss curve."""
    import matplotlib
    matplotlib.use("TkAgg" if show else "Agg")
    import matplotlib.pyplot as plt

    log_history = results.get("log_history", [])
    if not log_history:
        print("No training log found. Skipping plot.")
        return

    iters = [e["iter"] for e in log_history]
    train_losses = [e["train_loss"] for e in log_history]

    # Smooth
    window = max(1, len(train_losses) // 40)
    if window > 1:
        smooth = np.convolve(train_losses, np.ones(window) / window, mode="valid")
        smooth_iters = iters[window - 1:]
    else:
        smooth = train_losses
        smooth_iters = iters

    eval_iters = [e["iter"] for e in log_history if e["val_loss"] is not None]
    val_losses = [e["val_loss"] for e in log_history if e["val_loss"] is not None]

    best_val = results.get("best_val", {})
    best_loss = best_val.get("loss", 0)

    fig, ax = plt.subplots(figsize=(12, 5))

    ax.plot(iters, train_losses, alpha=0.18, color="#4dabf7", linewidth=0.5,
            label="Train Loss (raw)")
    ax.plot(smooth_iters, smooth, color="#1c7ed6", linewidth=2.2,
            label=f"Train Loss (smoothed, w={window})")
    if eval_iters:
        ax.plot(eval_iters, val_losses, "o-", color="#e03131", linewidth=2.0,
                markersize=6, markerfacecolor="white", markeredgewidth=2.0,
                label=f"Val Loss  (best = {best_loss:.4f})")

    ax.set_xlabel("Iteration", fontsize=12)
    ax.set_ylabel("Cross-Entropy Loss", fontsize=12)
    ax.set_title("LSTM Training on WikiText-2 — Loss Curve", fontsize=14, fontweight="bold")
    ax.legend(fontsize=11, framealpha=0.92, loc="upper right")
    ax.grid(True, alpha=0.25, linestyle="--")
    ax.set_xlim(left=0)
    ax.set_ylim(bottom=0)

    plt.tight_layout()
    path = os.path.join(output_dir, "loss_curve.png")
    fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
    print(f"Saved → {path}")

    if show:
        plt.show()
    else:
        plt.close(fig)


def main():
    # Resolve default paths relative to project dir (CWD-independent)
    project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    parser = argparse.ArgumentParser(description="Plot LSTM training loss curve")
    parser.add_argument("--results", default=os.path.join(project_dir, "out", "results.pkl"))
    parser.add_argument("--output", default=None)
    parser.add_argument("--no-show", action="store_true")
    args = parser.parse_args()

    if not os.path.exists(args.results):
        print(f"Error: {args.results} not found. Run training first.")
        return

    results = load_results(args.results)
    output_dir = args.output or os.path.dirname(args.results)
    plot_loss_curve(results, output_dir, show=not args.no_show)


if __name__ == "__main__":
    main()
